name: CI model to dockerhub

# Trigger
on:
  push:
    branches:
      -dev
  pull_request:
    branches:
      - dev

# Actions
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t sebassalvaradoo/regresion-lineal:v1 .

      - name: Docker push to Dockerhub
        run: docker push sebassalvaradoo/regresion-lineal:v1

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          password: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            if docker ps --all | grep regresion-lineal: then
              docker stop regresion-lineal
              docker rm regresion-lineal
            fi
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/regresion-lineal:v1
            docker run -d --name regresion-lineal -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/regresion-lineal:v1
